import { z } from 'zod'
import type { Heading } from './headings'

/**
 * F1-03 — the build-time content contract.
 * docs/CONTENT_STRATEGY.md §4, docs/ARCHITECTURE.md §8.
 *
 * "Validate at the boundary" is the single highest-value invariant in this
 * codebase: it is what makes "add a file" a safe publishing workflow. Every
 * frontmatter object passes through here, and a malformed one fails the
 * **build**, not the page.
 *
 * The length bounds are not decoration — they are the SEO limits from SEO.md §3
 * enforced at the point of authoring, so a truncated search snippet is a build
 * failure today rather than a discovery in Search Console in six months.
 *
 * Types are derived with `z.infer`, never written by hand, so a schema and its
 * type cannot drift.
 */

/**
 * A slug that can be a URL path segment and a filename on a case-insensitive
 * filesystem. Enforced rather than assumed: an uppercase letter here produces a
 * route that 404s on Linux and works locally on Windows, which is the worst
 * possible failure to debug.
 */
export const slugSchema = z
	.string()
	.regex(
		/^[a-z0-9]+(?:-[a-z0-9]+)*$/,
		'must be lowercase, hyphen-separated, no leading/trailing/double hyphens',
	)

/**
 * The controlled tag vocabulary. An unknown tag fails the build.
 *
 * A free-text tag field produces `nextjs`, `next-js`, and `Next.js` as three
 * separate archives within a year, each with one post. The cost of a closed list
 * is one edit here when a genuinely new subject appears; the cost of an open one
 * is a tag system nobody trusts.
 */
export const TAGS = [
	'architecture',
	'typescript',
	'react',
	'nextjs',
	'nodejs',
	'databases',
	'performance',
	'accessibility',
	'testing',
	'devops',
	'career',
] as const

export const tagSchema = z.enum(TAGS)
export type Tag = z.infer<typeof tagSchema>

/**
 * Shared frontmatter. Blog posts and case studies differ in their extra fields,
 * not in their identity, dates, or SEO surface — so those live once.
 */
const baseFrontmatter = z.object({
	// 10–70 chars: below 10 is not a title, above 70 is truncated in the SERP.
	title: z.string().min(10).max(70),

	/**
	 * `summary` does three jobs — the index hook, the meta description, and the
	 * feed description. One field, so they cannot drift, and its bounds are the
	 * meta-description bounds.
	 */
	summary: z.string().min(60).max(180),

	publishedAt: z.coerce.date(),
	updatedAt: z.coerce.date().optional(),

	draft: z.boolean().default(false),

	/** Generated by H-09 when absent. Must be site-absolute if present. */
	ogImage: z.string().startsWith('/').optional(),
})

export const postFrontmatterSchema = baseFrontmatter
	.extend({
		tags: z.array(tagSchema).min(1).max(5),
	})
	.strict() // an unknown key is a typo, and a silently ignored typo is the bug
	.refine((data) => !data.updatedAt || data.updatedAt >= data.publishedAt, {
		message: 'updatedAt cannot be earlier than publishedAt',
		path: ['updatedAt'],
	})

export type PostFrontmatter = z.infer<typeof postFrontmatterSchema>

/**
 * P-10 — a headline number, with the method that produced it.
 *
 * `method` IS REQUIRED, AND IT IS THE FIELD THAT MAKES THE REST CREDIBLE.
 * PROJECT_CASE_STUDIES.md §10 requires "a measurement method for every metric",
 * and PERSONAL_BRAND.md §3 rule 2 is "numbers or nothing". A number without a
 * method is an assertion wearing a number's clothes, and the schema is the only
 * place that rule can be enforced rather than remembered.
 *
 * `before`/`after` are strings rather than numbers because the units are part
 * of the value — "2.4s", "4.1%", "6 hours/day" — and a numeric field would push
 * the unit into a second field nobody would keep aligned.
 */
export const metricSchema = z
	.object({
		label: z.string().min(3).max(60),
		before: z.string().min(1).max(30).optional(),
		after: z.string().min(1).max(30),
		method: z.string().min(20).max(240),
	})
	.strict()

export type Metric = z.infer<typeof metricSchema>

export const caseStudyFrontmatterSchema = baseFrontmatter
	.extend({
		/**
		 * Skill ids, resolved against `content/skills.ts` by P-02. The
		 * cross-reference check is not here because this schema must stay usable
		 * without loading the skills table; F1-07 wires the two together.
		 */
		stack: z.array(slugSchema).min(1).max(12),
		role: z.string().min(3).max(80),
		/** Index ordering. Lower sorts first. */
		order: z.number().int().nonnegative(),

		/**
		 * THE ONE-LINE PROBLEM, NOT A DESCRIPTION — WEBSITE_STRUCTURE.md §4.6.
		 * The index entry leads with this, because "what was wrong" routes a
		 * reader to the right case study and "what it is" does not.
		 */
		problem: z.string().min(40).max(200),

		/** When the work happened. `YYYY-MM` bounds, formatted at render. */
		period: z
			.object({
				from: z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),
				to: z
					.string()
					.regex(/^\d{4}-(0[1-9]|1[0-2])$/)
					.optional(),
			})
			.strict(),

		/**
		 * One to four outcome metrics. The first is the headline the index card
		 * shows, so the ordering is editorial rather than incidental.
		 */
		metrics: z.array(metricSchema).min(1).max(4),

		/** Exactly one may be featured first on Home — H-03 takes the top three. */
		featured: z.boolean().default(false),

		/** Repository, live site, write-up. Absent is normal and fine. */
		links: z
			.array(
				z
					.object({
						label: z.string().min(2).max(30),
						href: z.string().url(),
					})
					.strict(),
			)
			.max(4)
			.default([]),

		/**
		 * Set while the study is written from a template rather than from the
		 * author's own project. It is a *content* flag, not a draft flag: the page
		 * builds and is reachable, and `/projects` marks it. Nothing on this site
		 * should present unreviewed work as a verified record.
		 */
		needsReview: z.boolean().default(false),
	})
	.strict()

export type CaseStudyFrontmatter = z.infer<typeof caseStudyFrontmatterSchema>

/** What the case-study loader returns. Mirrors `Post`. */
export interface CaseStudy {
	slug: string
	frontmatter: CaseStudyFrontmatter
	readingTimeMinutes: number
	href: string
	headings: Heading[]
}

/** What a loader returns: validated frontmatter plus everything derived. */
export interface Post {
	slug: string
	frontmatter: PostFrontmatter
	/** Minutes, rounded up, from the raw MDX body. */
	readingTimeMinutes: number
	/** Site-absolute, with the trailing slash GitHub Pages needs. */
	href: string
	/** `##` headings, for the table of contents — see `headings.ts`. */
	headings: Heading[]
}
